Preview events
path-cc/path-cc.github.io pull request #355
Opened 2023-03-29 18:16 UTC by hannahcheren

https://path-cc.io/web-preview/preview-events/events/OSG-User-School-2023/

2023-03-31 21:03 UTC, osg-cat requested changes
Comments:

- Shorten the title so it fits better: title: "OSG User School 2023, August 7–11" => "OSG User School 2023, Aug. 7–11"

- In the metadata, change the link: link: "https://opensciencegrid.org/user-school-2023/#applications" => "https://osg-htc.org/user-school-2023/". I just want this (events) page to link to the overall home page, nothing extra.

- Please find an image from a past in-person School, rather than something generic (and yes, I know what’s on the School’s home page). If Janet does not have images to choose from, we can find a time for you to look through my collection.

- There’s just too much repetition of ideas and words here. We need appealing content!

2023-03-31 21:03 UTC, osg-cat commented on _events/OSG-User-School-2023.md
>  The OSG User School will occur on August 7–11, where you will learn to use high-throughput computing (HTC) systems to run large-scale computing applications at your campus or using the national-scale
As the first content line of this page, could it be made more interesting and appealing?

2023-03-31 21:03 UTC, osg-cat commented on _events/OSG-User-School-2023.md
>  Applications are now open. The deadline for applications is Monday, 17 April 2023. Submit your application soon to ensure consideration!
I don’t think that this information belongs here.

2023-03-31 21:03 UTC, osg-cat commented on _events/OSG-User-School-2023.md
>  To apply, complete the [online application form](https://uwmadison.co1.qualtrics.com/jfe/form/SV_9shkUL5ZDSghKvk) and have someone email a letter of recommendation for you to [user-school@osg-htc.org
Remove.

2023-03-31 21:03 UTC, osg-cat commented on _events/OSG-User-School-2023.md
>  For more information about the School and to stay up-to-date with any announcements, please visit the [OSG User School 2023 site](https://osg-htc.org/user-school-2023/).
Remove.

2023-03-31 21:03 UTC, osg-cat commented on _events/OSG-User-School-2023.md
> +To learn more about the event, check out these articles written about the OSG User School 2022:
Instead of just a list of links, can each one have a sentence or so that might actually draw people in?

2023-04-03 19:34 UTC, osg-cat requested changes
I think this is getting pretty close. Please make the new changes, then carefully check over one more time, then go ahead and post.

2023-04-03 19:34 UTC, osg-cat commented on _events/OSG-User-School-2023.md
> +- This article spotlights [studens from the NIAID/ACE students who attended this year’s OSG User School 2022](https://osg-htc.org/spotlights/NIAID-ACE-students-attend-OSG-User-School.html). Learn mor
“students”

2023-04-03 19:34 UTC, osg-cat commented on _events/OSG-User-School-2023.md
> +- This article spotlights [studens from the NIAID/ACE students who attended this year’s OSG User School 2022](https://osg-htc.org/spotlights/NIAID-ACE-students-attend-OSG-User-School.html). Learn mor
Need to spell out NIAID and ACE on first use.

2023-04-03 19:34 UTC, osg-cat commented on _events/OSG-User-School-2023.md
> +The OSG User School provides researchers the opportunity to learn how to use high-throughput computing (HTC) systems to run large-scale computing applications at their campus or using the national-sc
“OSG Consortium” [capital C]

2023-04-03 19:34 UTC, osg-cat commented on _events/OSG-User-School-2023.md
> +The OSG User School provides researchers the opportunity to learn how to use high-throughput computing (HTC) systems to run large-scale computing applications at their campus or using the national-sc
Replace paragraph with:

“
Has your research computing outgrown your available capacity? How could access to **lots** more computing transform your research or that of others? If you have research workloads that can be broken into many independent, parallel computing tasks, we can help.

The OSG User School provides researchers the opportunity to learn how to use high-throughput computing (HTC) systems to run large-scale computing applications at their campus or using the national-scale OSG consortium.
”

[Or feel free to edit, but the existing paragraph has two sentences that say almost the same thing. I stole the other text from our announcement email.]

2023-04-03 19:34 UTC, osg-cat commented on _events/OSG-User-School-2023.md
> +
Add:

“
<span style="font-size: larger; color: #FF6600;">Apply by April 17 on [the OSG School website](https://osg-htc.org/user-school-2023/).</span>
”

[Yes, it repeats the stuff on the right, but I’m fine with this here.]

2023-04-03 19:43 UTC, hannahcheren commented
> I think this is getting pretty close. Please make the new changes, then carefully check over one more time, then go ahead and post.

2023-04-03 19:43 UTC, closed without merging